const $=s=>document.querySelector(s),KEY='sc3',now=Date.now,esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const bc=new BroadcastChannel('sc3'),tm=t=>new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),wardOf=(x,y)=>x<50?(y<30?3:12):(y<30?7:9);
const WN={3:[25,15],7:[75,15],12:[25,45],9:[75,45]},CATS=['Overflowing bin','Illegal dumping','Missed pickup','Plastic waste','E-waste','Construction waste','Roadside waste','Organic waste','Mixed waste','Other'];
const WT=['Organic','Plastic','Paper','Metal','Glass','E-waste','Mixed'],RECY=['Plastic','Paper','Metal','Glass','E-waste'],PR={HIGH:3,MED:2,LOW:1};
const ST={SUBMITTED:['🔴','Submitted'],ASSIGNED:['🔵','Assigned'],IN_PROGRESS:['🟡','In progress'],RESOLVED:['🟢','Resolved'],MISSED:['⚠️','Missed']};
const bd=s=>`<span class="bd ${s}">${ST[s][0]} ${ST[s][1]}</span>`,pb=p=>({HIGH:'🔺 High',MED:'🔶 Medium',LOW:'🔹 Low'}[p]);
const L={en:{hi:'Good day! 👋',tap:'Tap & speak',rep:'Report Waste',mine:'My Complaints',ask:'Register your complaint?',done:'Your complaint has been registered.',yes:'Yes',no:'No',sub:'Submit complaint',can:'Cancel',listen:'Listening…',think:'Understanding…',help:'Try saying: There is a lot of garbage here.',none:'No complaints yet. Your reports will appear here.',sr:'en-IN',review:'Check the text, add a photo if you like, then submit.',st:'Status of your latest complaint: '},
te:{hi:'నమస్కారం! 👋',tap:'మాట్లాడండి',rep:'చెత్త నివేదించు',mine:'నా ఫిర్యాదులు',ask:'మీ ఫిర్యాదును నమోదు చేయనా?',done:'మీ ఫిర్యాదు నమోదు చేయబడింది.',yes:'అవును',no:'వద్దు',sub:'ఫిర్యాదు సమర్పించండి',can:'రద్దు',listen:'వింటున్నాను…',think:'అర్థం చేసుకుంటున్నాను…',help:'ఇలా చెప్పండి: ఇక్కడ చాలా చెత్త ఉంది.',none:'ఇంకా ఫిర్యాదులు లేవు.',sr:'te-IN',review:'వచనాన్ని చూడండి, కావాలంటే ఫోటో జోడించి, సమర్పించండి.',st:'మీ తాజా ఫిర్యాదు స్థితి: '},
hi:{hi:'नमस्ते! 👋',tap:'बोलिए',rep:'कचरा रिपोर्ट करें',mine:'मेरी शिकायतें',ask:'क्या मैं आपकी शिकायत दर्ज करूँ?',done:'आपकी शिकायत दर्ज हो गई है।',yes:'हाँ',no:'नहीं',sub:'शिकायत सबमिट करें',can:'रद्द करें',listen:'सुन रहा हूँ…',think:'समझ रहा हूँ…',help:'कहिए: यहाँ बहुत कचरा है।',none:'अभी कोई शिकायत नहीं।',sr:'hi-IN',review:'टेक्स्ट देखें, चाहें तो फोटो जोड़ें, फिर सबमिट करें।',st:'आपकी ताज़ा शिकायत की स्थिति: '}};
const T=k=>L[U.lg][k];
function mk(n,cat,x,y,pri,st,o={}){const t=now()-(1050-n)*2e6,c={id:'SC-'+n,cat,desc:'',x,y,ward:wardOf(x,y),pri,st,w:null,t,hist:[['SUBMITTED',t]],...o};if(st=='RESOLVED'){c.hist.push(['RESOLVED',t+9e5]);c.rt=t+9e5}return c}
const oldC=()=>{const T=['Plastic','Organic','Paper','Mixed','Metal','Glass','Organic','Mixed'],K=[60,120,45,190,38,52,140,170],C=['Plastic waste','Overflowing bin','Roadside waste','Illegal dumping','E-waste','Construction waste','Organic waste','Roadside waste'],r=[];for(let i=0;i<18;i++){const c=mk(1000+i,C[i%8],8+(i*37)%84,5+(i*23)%50,['HIGH','MED','LOW'][i%3],'RESOLVED',{kg:K[i%8]+i*3,wt:T[i%8]}),s=((i%7)+1)*864e5+(i%5)*3e6;c.t-=s;c.rt-=s;c.hist=c.hist.map(h=>[h[0],h[1]-s]);r.push(c)}
const m=(n,x,y,why,sh)=>{const c=mk(n,'Missed pickup',x,y,'MED','MISSED',{mr:why,w:'w2'});c.t-=sh;c.hist=[['SUBMITTED',c.t],['ASSIGNED',c.t+3e5],['MISSED',c.t+9e5]];return c};r.push(m(1030,70,20,'Vehicle unavailable',0),m(1031,20,48,'Road inaccessible',1.7e8));return r};
const seed=()=>({nid:0,n:1044,c:[...oldC(),mk(1038,'Plastic waste',72,12,'MED','RESOLVED',{kg:60,wt:'Plastic'}),mk(1039,'Roadside waste',30,15,'LOW','RESOLVED',{kg:95,wt:'Organic'}),mk(1040,'Illegal dumping',80,45,'HIGH','RESOLVED',{kg:210,wt:'Mixed'}),mk(1041,'Overflowing bin',18,40,'HIGH','RESOLVED',{kg:185,wt:'Mixed',me:1}),mk(1042,'Missed pickup',62,50,'MED','SUBMITTED',{me:1}),mk(1043,'Construction waste',40,20,'HIGH','SUBMITTED')],w:[{id:'w1',n:'Ravi',v:'V07',duty:0,mode:''},{id:'w2',n:'Anita',v:'V03',duty:0,mode:''}],notes:[],act:[[now()-6e5,'🟢 System ready (demo data)']]});
let NID=()=>S.n++,BLOC=()=>{};
let load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}};
let S=load(),LOC={};const U={lg:'en',cv:'home',vs:'idle',wid:'w1',px:25,py:45,ws:12,seen:S.nid,f:'',kg:'',txt:'',q:'',ans:''};
let save=()=>{try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){}bc.postMessage({t:'s'})},commit=()=>{save();R()};
let log=m=>{S.act.unshift([now(),m]);S.act=S.act.slice(0,14)},note=(to,m)=>{S.notes.push({id:++S.nid,to,m});S.notes=S.notes.slice(-30);log(m)};
const setSt=(c,s)=>{c.hist.push([s,now()]);c.st=s;if(s=='RESOLVED')c.rt=now()};
const PHI=/hospital|school|child|kids|baby|elder|disease|dengue|malaria|cholera|infection|health|sick|dead|carcass|blood|hazard|toxic|chemical|medical|fire|burn|block|drain|sewage|overflow|stink|smell|foul|rotten|rotting|maggot|mosquito|rats?\b|days|week|since|many|huge|lot|heavy|everywhere|urgent|emergency|danger|ఆసుపత్రి|పాఠశాల|పిల్లలు|దుర్వాసన|వాసన|కంపు|చాలా|రోజులు|వారం|అత్యవసర|ప్రమాద|అస్పతాల|स्कूल|बच्चे|बदबू|दुर्गंध|बहुत|दिन|हफ्ते|खतरा|अस्पताल|तुरंत|बीमारी|नाली/gi,PLO=/small|little|minor|slight|single|one bottle|few|కొంచెం|చిన్న|కొద్ది|थोड़ा|थोड़ी|छोटा|कुछ/gi,PB={'Overflowing bin':2,'Illegal dumping':2,'Missed pickup':2};
const PRI=(t='',cat)=>{const n=(PB[cat]||1)+Math.min(3,(t.match(PHI)||[]).length)-Math.min(2,(t.match(PLO)||[]).length);return n>=3?'HIGH':n<=0?'LOW':'MED'};
const AI=(t='',cat)=>{const k=[[/overflow|full|bin|నిండ|భరా|भरा/i,'Overflowing bin',.92,'HIGH'],[/dump|illegal/i,'Illegal dumping',.87,'HIGH'],[/missed|not collected|రాలేదు|नहीं आया/i,'Missed pickup',.9,'HIGH'],[/plastic|bottle|ప్లాస్టిక్|प्लास्टिक/i,'Plastic waste',.88,'MED'],[/e-?waste|electronic/i,'E-waste',.84,'MED'],[/construct|debris|brick|sand/i,'Construction waste',.85,'MED'],[/food|organic|wet|vegetable/i,'Organic waste',.83,'MED'],[/చాలా|lot|heavy|smell|stink|बहुत/i,'Overflowing bin',.8,'HIGH']];
const h=k.find(r=>r[0].test(t+' '+(cat||'')));const c=h?h[1]:(cat||'Mixed waste');return{cat:c,conf:h?h[2]:.6,pri:PRI(t,c)}};
function busy(p){const a=document.activeElement;if(a&&p.contains(a)&&/INPUT|TEXTAREA/.test(a.tagName)&&a.type!='file'){U.dirty=1;return 1}}
const mapH=o=>`<svg class="map" viewBox="0 0 100 60" ${o.click?'data-m=1':''} role="img" aria-label="Ward map">${Object.entries(WN).map(([w,[x,y]])=>`<rect x="${x-24.5}" y="${y-14.5}" width="49" height="29" rx="2" class="wd"/><text x="${x}" y="${y-9}" class="wl">Ward ${w}</text>`).join('')}<path d="M0 30H100M50 0V60M10 8L90 54" class="rd"/>${o.pin?`<g style="transform:translate(${U.px}px,${U.py}px)"><text class="pt" y="-1">📍</text></g>`:S.c.map(c=>`<g class="cm ${c.st}" style="transform:translate(${c.x}px,${c.y}px)" tabindex="0" role="button" data-a="sel" data-v="${c.id}" aria-label="${c.id} ${ST[c.st][1]}"><circle class="pl" r="2.2"/><circle r="2.2"/><text>${{SUBMITTED:'!',ASSIGNED:'→',IN_PROGRESS:'▶',MISSED:'✕',RESOLVED:'✓'}[c.st]}</text></g>`).join('')+S.w.map(w=>{const p=LOC[w.v]||{x:50,y:30};return`<g id="v${w.v}" class="vh ${w.duty?'on':''}" style="transform:translate(${p.x}px,${p.y}px)"><circle r="3.4"/><text class="vt">🚛</text><text y="6" class="vl">${w.v}</text></g>`}).join('')}</svg>`;
/* LOCATION + MAP */
const CEN=(window.SC_CONFIG||{}).center||[17.385,78.4867],KX=111320*Math.cos(CEN[0]*Math.PI/180)/100,KY=111320/100,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const toXY=(la,ln)=>[cl(50+(ln-CEN[1])*KX,3,97),cl(30-(la-CEN[0])*KY,3,57)];
let MAP,MK,CI,GW=null,GT=0,FOL=1,ICM=0,DOT,PIN;
function setPos(la,ln,acc){U.lat=la;U.lng=ln;U.acc=acc||0;[U.px,U.py]=toXY(la,ln);U.ws=wardOf(U.px,U.py);U.gm=`📍 ${la.toFixed(5)}, ${ln.toFixed(5)}${acc?` · ±${Math.round(acc)} m live GPS${acc>100?' · ⚠ approximate (laptop/Wi-Fi). Use a phone for exact GPS':''}`:' · pin placed by you'} · Ward ${U.ws}`;
 if(MAP){MK.setLatLng([la,ln]);CI.setLatLng([la,ln]).setRadius(acc||0);if(ICM!=(U.manual?1:0)){ICM=U.manual?1:0;MK.setIcon(ICM?PIN:DOT)}if(!U.manual&&FOL)MAP.setView([la,ln],Math.max(MAP.getZoom(),17))}updGm()}
const updGm=()=>{const e=$('#gm');if(e)e.textContent=U.gm||''};
function gpsStart(){if(GW!=null)return;if(!navigator.geolocation){U.gm='Location is not available on this device. Tap the map to place the pin.';return updGm()}U.gm='Finding your location…';GW=navigator.geolocation.watchPosition(p=>{if(U.manual)return;const a=p.coords.accuracy,n=Date.now();if(U.lat!=null&&U.acc&&a>U.acc*2&&n-GT<8000)return;GT=n;setPos(p.coords.latitude,p.coords.longitude,a)},e=>{U.gm=e.code==1?'Location permission is required for automatic location. Allow it in the address bar, or tap the map to place the pin.':'Waiting for a GPS signal…';updGm()},{enableHighAccuracy:true,maximumAge:0,timeout:30000})}
function gpsStop(){if(GW!=null){navigator.geolocation.clearWatch(GW);GW=null}}
function initMap(){const e=$('#rmap');if(MAP){MAP.remove();MAP=null}if(!e||!window.L){return}const c=U.lat!=null?[U.lat,U.lng]:CEN;const LF=window.L;MAP=LF.map(e).setView(c,U.lat!=null?17:12);FOL=1;const st=LF.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(MAP),sat=LF.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});LF.control.layers({Map:st,Satellite:sat},null,{position:'topright'}).addTo(MAP);DOT=LF.divIcon({className:'me',html:'<span class="medot"></span>',iconSize:[22,22],iconAnchor:[11,11]});PIN=new LF.Icon.Default();ICM=U.manual?1:0;MK=LF.marker(c,{draggable:true,icon:ICM?PIN:DOT}).addTo(MAP);CI=LF.circle(c,{radius:U.acc||0,weight:1,color:'#1a73e8',fillColor:'#1a73e8',fillOpacity:.15}).addTo(MAP);MAP.on('dragstart',()=>{FOL=0});
 MK.on('dragend',()=>{const p=MK.getLatLng();U.manual=1;setPos(p.lat,p.lng)});MAP.on('click',ev=>{U.manual=1;setPos(ev.latlng.lat,ev.latlng.lng)});updGm()}
const lgc=()=>`<div class="chips" role="group" aria-label="Language">${[['en','English'],['te','తెలుగు'],['hi','हिन्दी']].map(([l,n])=>`<button class="chip ${U.lg==l?'on':''}" data-a="lg" data-v="${l}" aria-pressed="${U.lg==l}">${n}</button>`).join('')}</div>`;
/* CITIZEN */
const trk=c=>{const i={SUBMITTED:0,ASSIGNED:1,MISSED:1,IN_PROGRESS:2,RESOLVED:3}[c.st],last=c.hist[c.hist.length-1][1];return`<div class="card"><div class="row"><b>#${c.id}</b>${bd(c.st)}</div><p class="m">${esc(c.cat)} · Ward ${c.ward}</p>${c.img?`<img class="th" src="${c.img}" alt="Photo of reported waste">`:''}<ol class="tl">${['Submitted','Assigned','In progress','Resolved'].map((s,j)=>{const dn=j<i||c.st=='RESOLVED';return`<li class="${dn?'d':j==i?'n':''}"><span>${dn?'✓':j==i?'●':'○'}</span>${s}${j==i||dn&&j==3?`<small>${tm(last)}</small>`:''}</li>`}).join('')}</ol>${c.st=='RESOLVED'&&c.proof?`<p class="m">✅ Cleaned — photo from the worker</p><img class="th" src="${c.proof}" alt="Photo after cleaning">`:''}${c.st=='MISSED'?'<p class="al">⚠️ Pickup missed. It will be rescheduled.</p>':''}</div>`};
const aib=()=>{const a=AI(U.desc,U.cat);return`🤖 <b>AI suggestion</b> <span class="tag">DEMO heuristic</span><br>${a.cat} · ${Math.round(a.conf*100)}% · ${pb(a.pri)} priority<br><small class="m">Priority is decided automatically from your description. You can change the category.</small>`};
function rc(){const p=$('#pc');if(busy(p))return;const m=S.c.filter(c=>c.me).reverse();let h;
if(U.cv=='report'){const a=AI(U.desc,U.cat);h=`<div class="col card pad"><h2>${T('rep')}</h2>${U.rv?`<p class="rp" role="status">${esc(T('review'))}</p>`:''}<p class="lb">1 · Location <small class="m">live GPS · drag the pin to adjust</small></p><div id="rmap" role="application" aria-label="Map. Drag the pin to adjust your location"></div><p class="m" id="gm" role="status">${esc(U.gm||'')}</p><button class="btn sec" data-a="gps">📍 Use my live location</button><p class="lb">2 · Category</p><div class="chips">${CATS.map(c=>`<button class="chip ${(U.cat||a.cat)==c?'on':''}" data-a="cat" data-v="${c}" aria-pressed="${(U.cat||a.cat)==c}">${c}</button>`).join('')}</div></div><div class="col card pad"><p class="lb" style="margin-top:0">3 · Photo</p><div class="yn"><button class="btn sec" data-a="cam" data-v="img">📷 Take photo</button><label class="btn sec">🖼️ Upload<input class="vh0" type="file" accept="image/*" data-c="img"></label></div>${U.img?`<img class="th" src="${U.img}" alt="Your photo">`:''}<p class="lb">4 · Describe <small class="m">type or speak</small></p>${lgc()}<button class="btn sec" data-a="mic">🎙️ ${U.vs=='listen'?T('listen'):'Speak your report'}</button><textarea data-u="desc" rows="3" aria-label="Description" placeholder="What do you see?">${esc(U.desc||'')}</textarea><div class="ai" id="aib">${aib()}</div><button class="btn big" data-a="submit">Submit report</button></div>`}
else if(U.cv=='list')h=`<div class="col"><h2>${T('mine')}</h2>`+(m.map(trk).join('')||`<p class="em">${T('none')}</p>`)+'</div>';
else h=`<div class="col card pad"><p class="hi">${T('hi')}</p><div class="chips" role="group" aria-label="Language">${[['en','English'],['te','తెలుగు'],['hi','हिन्दी']].map(([l,n])=>`<button class="chip ${U.lg==l?'on':''}" data-a="lg" data-v="${l}" aria-pressed="${U.lg==l}">${n}</button>`).join('')}</div><button class="mic ${U.vs}" data-a="mic" aria-label="${T('tap')}"><span class="wv"><i></i><i></i><i></i><i></i><i></i></span><span class="mi">${{idle:'🎙️',listen:'🎙️',proc:'✨',speak:'🔊'}[U.vs]}</span>${{idle:T('tap'),listen:T('listen'),proc:T('think'),speak:'🔊'}[U.vs]}</button>${U.tr?`<p class="tr">“${esc(U.tr)}”</p>`:''}${U.rp?`<p class="rp" role="status">${esc(U.rp)}</p>`:''}${U.pend?`<div class="yn"><button class="btn" data-a="yes">✅ ${T('sub')}</button><button class="btn sec" data-a="no">✖ ${T('can')}</button></div>`:''}<div class="tx"><input data-u="txt" value="${esc(U.txt)}" placeholder="Or type here…" aria-label="Type instead of speaking"><button class="btn" data-a="send">Send</button></div></div><div class="col"><div class="card pad"><p class="lb" style="margin-top:0">📍 Your live location <small class="m">drag the pin to adjust</small></p><div id="rmap" style="height:200px" role="application" aria-label="Map showing your live location"></div><p class="m" id="gm" role="status">${esc(U.gm||'')}</p><button class="btn sec" data-a="gps">📍 Use my live location</button></div><div class="tiles"><button class="tile" data-a="cv" data-v="report"><span>📸</span>${T('rep')}</button><button class="tile" data-a="cv" data-v="list"><span>📍</span>${T('mine')}</button></div><div class="card"><b>🚛 Next collection</b><p class="m">Today 6:30–7:00 PM · Ward 12 <span class="tag">DEMO schedule</span></p></div>${m[0]?trk(m[0]):''}</div>`;
p.innerHTML=`<div class="ph-h">${U.cv!='home'?'<button class="ib" data-a="cv" data-v="home" aria-label="Back">←</button>':'<span>Citizen portal</span>'}<span class="tag">Citizen</span></div><div class="bd2">${h}</div>`;if(U.cv=='list')gpsStop();else{gpsStart();initMap();updGm()}}
const say=t=>{U.rp=t;U.vs='speak';rc();try{const u=new SpeechSynthesisUtterance(t);u.lang=T('sr');u.onend=u.onerror=()=>{U.vs='idle';rc()};speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){U.vs='idle'}setTimeout(()=>{if(U.vs=='speak'){U.vs='idle';rc()}},4500)};
const IN={YES:/^(yes|yeah|ok|okay|confirm|అవును|సరే|हाँ|हां|ठीक)/i,NO:/^(no|cancel|stop|వద్దు|కాదు|नहीं|रद्द)/i,CHECK:/status|check|track|where|స్థితి|ఎక్కడ|स्थिति|कहाँ/i,REPORT:/waste|garbage|trash|dump|litter|smell|miss|చెత్త|కచరా|రాలేదు|कचरा|गंदगी|नहीं आया/i};
function handle(t){U.tr=t;U.txt='';if(IN.CHECK.test(t)){const c=S.c.filter(c=>c.me).pop();return say(c?T('st')+ST[c.st][1]+' ('+c.id+')':T('none'))}
if(U.pend&&t.length<20&&IN.YES.test(t))return A.yes();if(U.pend&&t.length<20&&IN.NO.test(t))return A.no();U.pend={desc:t};say(T('ask'))}
function newReport(d,cat,extra={}){const a=AI(d,cat),c=mk(NID(),cat||a.cat,U.px,U.py,a.pri,'SUBMITTED',{me:1,desc:d,ai:{cat:a.cat,conf:a.conf},lat:U.lat,lng:U.lng,t:now(),...extra});c.hist=[['SUBMITTED',now()]];S.c.push(c);note('op',`🔴 NEW ${c.pri} complaint — Ward ${c.ward}: ${c.cat}`);note('cit',`✅ ${c.id} submitted`);return c}
/* WORKER */
const dist=(w,c)=>{const p=LOC[w.v]||{x:50,y:30},d=Math.hypot(c.x-p.x,c.y-p.y);return`${(d*.04).toFixed(1)} km · ETA ${Math.max(1,Math.round(d*.15))} min`};
const WL={en:{left:'left',dn:'done',on:'Start work',off:'Stop work',onS:'You are on duty',none:'No tasks now. New tasks will appear here.',ward:'Ward',hear:'Listen',go:'Go to place',st:'START',photo:'Take photo',up:'Choose photo',sub:'SUBMIT',hint:'Take a photo of the cleaned place first',well:'Well done!',miss:'Could not collect',why:'Why?',s1:'After cleaning, take a photo and press Submit.',say:(w,c,p,k)=>`New task. Ward ${w}. ${c}. Priority: ${p}. About ${k} kilometre away. Press the map button to go there, then press Start.`,pr:{HIGH:'Urgent',MED:'Normal',LOW:'Low'},rs:{'Vehicle unavailable':'Vehicle problem','Road inaccessible':'Road blocked','Waste not present':'No waste there','Location issue':'Wrong place',Other:'Other'},cat:{}},
te:{left:'మిగిలినవి',dn:'పూర్తి',on:'పని ప్రారంభించు',off:'పని ఆపు',onS:'మీరు డ్యూటీలో ఉన్నారు',none:'ఇప్పుడు పనులు లేవు. కొత్త పనులు ఇక్కడ కనిపిస్తాయి.',ward:'వార్డు',hear:'వినండి',go:'స్థలానికి వెళ్ళండి',st:'ప్రారంభించు',photo:'ఫోటో తీయండి',up:'ఫోటో ఎంచుకోండి',sub:'సమర్పించు',hint:'ముందు శుభ్రం చేసిన చోటు ఫోటో తీయండి',well:'చాలా బాగుంది!',miss:'సేకరించలేకపోయాను',why:'ఎందుకు?',s1:'శుభ్రం చేసిన తర్వాత ఫోటో తీసి సమర్పించు నొక్కండి.',say:(w,c,p,k)=>`కొత్త పని. వార్డు ${w}. ${c}. ప్రాధాన్యత: ${p}. సుమారు ${k} కిలోమీటర్ల దూరం. మ్యాప్ బటన్ నొక్కి అక్కడికి వెళ్లండి, తర్వాత ప్రారంభించు నొక్కండి.`,pr:{HIGH:'అత్యవసరం',MED:'సాధారణం',LOW:'తక్కువ'},rs:{'Vehicle unavailable':'వాహనం సమస్య','Road inaccessible':'రోడ్డు మూసుకుంది','Waste not present':'చెత్త లేదు','Location issue':'చోటు తప్పు',Other:'ఇతర'},cat:{'Overflowing bin':'నిండిపోయిన చెత్త డబ్బా','Illegal dumping':'అక్రమంగా చెత్త పారవేత','Missed pickup':'చెత్త సేకరణ మిస్ అయింది','Plastic waste':'ప్లాస్టిక్ చెత్త','E-waste':'ఈ-వేస్ట్','Construction waste':'నిర్మాణ వ్యర్థాలు','Roadside waste':'రోడ్డు పక్క చెత్త','Organic waste':'తడి చెత్త','Mixed waste':'మిశ్రమ చెత్త',Other:'ఇతర చెత్త'}},
hi:{left:'बाकी',dn:'पूरे',on:'काम शुरू करें',off:'काम बंद करें',onS:'आप ड्यूटी पर हैं',none:'अभी कोई काम नहीं। नया काम यहाँ दिखेगा।',ward:'वार्ड',hear:'सुनें',go:'जगह पर जाएं',st:'शुरू करें',photo:'फोटो लें',up:'फोटो चुनें',sub:'सबमिट करें',hint:'पहले साफ जगह की फोटो लें',well:'शाबाश!',miss:'नहीं उठा सका',why:'क्यों?',s1:'सफाई के बाद फोटो लें और सबमिट दबाएं।',say:(w,c,p,k)=>`नया काम। वार्ड ${w}। ${c}। प्राथमिकता: ${p}। लगभग ${k} किलोमीटर दूर। मैप बटन दबाकर वहाँ जाएं, फिर शुरू करें दबाएं।`,pr:{HIGH:'जरूरी',MED:'सामान्य',LOW:'कम'},rs:{'Vehicle unavailable':'गाड़ी की समस्या','Road inaccessible':'रास्ता बंद है','Waste not present':'कचरा नहीं है','Location issue':'जगह गलत है',Other:'अन्य'},cat:{'Overflowing bin':'भरा हुआ कूड़ेदान','Illegal dumping':'अवैध कचरा फेंकना','Missed pickup':'कचरा उठाना छूट गया','Plastic waste':'प्लास्टिक कचरा','E-waste':'ई-कचरा','Construction waste':'निर्माण का मलबा','Roadside waste':'सड़क किनारे कचरा','Organic waste':'गीला कचरा','Mixed waste':'मिला-जुला कचरा',Other:'अन्य कचरा'}}};
const W=k=>WL[U.lg][k];
const speakW=t=>{try{const u=new SpeechSynthesisUtterance(t);u.lang=T('sr');speechSynthesis.cancel();speechSynthesis.speak(u)}catch(e){}};
const km=(w,c)=>{const p=LOC[w.v]||{x:50,y:30};return(Math.hypot(c.x-p.x,c.y-p.y)*.04).toFixed(1)},sayT=(w,c)=>c.st=='ASSIGNED'?W('say')(c.ward,W('cat')[c.cat]||c.cat,W('pr')[c.pri],km(w,c)):W('s1');
function rw(){const p=$('#pw');if(busy(p))return;if(!S.w.find(x=>x.id==U.wid)){p.innerHTML='<div class="ph-h"><span>Worker portal</span><span class="tag">Worker</span></div><p class="em">No worker profile is linked to this account yet. Ask an admin.</p>';return}const w=S.w.find(x=>x.id==U.wid),mine=S.c.filter(c=>c.w==w.id),todo=mine.filter(c=>c.st=='ASSIGNED'||c.st=='IN_PROGRESS').sort((a,b)=>(b.st=='IN_PROGRESS')-(a.st=='IN_PROGRESS')||PR[b.pri]-PR[a.pri]),dn=mine.filter(c=>c.st=='RESOLVED').length,cur=todo[0];
const sel=document.body.dataset.live?'':`<select data-c="wid" aria-label="Choose worker">${S.w.map(x=>`<option value="${x.id}" ${x.id==w.id?'selected':''}>${x.n} · ${x.v}</option>`).join('')}</select>`;
let h=`${sel}${lgc()}<div class="wsum"><span>📋 <b>${todo.length}</b> ${W('left')}</span><span>✅ <b>${dn}</b> ${W('dn')}</span></div><button class="btn big wbtn ${w.duty?'sec':''}" data-a="duty">${w.duty?'⏹ '+W('off'):'▶ '+W('on')}</button>${w.duty?`<p class="m">${w.mode=='GPS'?'🟢 GPS':'<span class="tag">DEMO</span>'} ${W('onS')}</p>`:''}`;
if(!cur)h+=`<p class="em">${W('none')}</p>`;
else{h+=`<div class="card"><div class="wpr ${cur.pri}">${{HIGH:'🔺',MED:'🔶',LOW:'🔹'}[cur.pri]} ${W('pr')[cur.pri]}</div><h3 class="wh">${W('ward')} ${cur.ward} · ${esc(W('cat')[cur.cat]||cur.cat)}</h3><p class="m wd">📍 ${cur.lat!=null?cur.lat.toFixed(4)+', '+cur.lng.toFixed(4):W('ward')+' '+cur.ward}</p><p class="m wd">🚚 <span id="dist">${dist(w,cur)}</span></p>${cur.desc?`<p class="m">“${esc(cur.desc)}”</p>`:''}${cur.img?`<img class="th" src="${cur.img}" alt="">`:''}<div class="wr"><button class="btn sec wbtn" data-a="hear">🔊 ${W('hear')}</button>${cur.lat!=null?`<a class="btn sec wbtn" href="https://www.google.com/maps/dir/?api=1&destination=${cur.lat},${cur.lng}&travelmode=driving" target="_blank" rel="noopener">🧭 ${W('go')}</a>`:''}</div>`;
if(cur.st=='ASSIGNED')h+=`<button class="btn big wbtn" data-a="start">▶ ${W('st')}</button>`;
else h+=`<div class="ws ${U.proof?'ok':''}"><div class="wn">${U.proof?'✓':'📷'}</div><div class="wb"><div class="wr"><button class="btn wbtn" data-a="cam" data-v="proof">📷 ${W('photo')}</button><label class="btn sec wbtn">🖼️ ${W('up')}<input class="vh0" type="file" accept="image/*" data-c="proof"></label></div>${U.proof?`<img class="th" src="${U.proof}" alt="">`:''}</div></div><button class="btn big wbtn" data-a="done" ${U.proof?'':'disabled'}>✅ ${W('sub')}</button>${U.proof?'':`<p class="m wd">👆 ${W('hint')}</p>`}<button class="btn sec wbtn" data-a="missq">❌ ${W('miss')}</button>${U.mq?`<p class="lb">${W('why')}</p><div class="wg">${Object.keys(W('rs')).map(x=>`<button class="wt2" data-a="miss" data-v="${x}">${W('rs')[x]}</button>`).join('')}</div>`:''}`;
h+=`</div><div class="card">${todo.map((c,i)=>`<div class="row"><span>${i?'○':'➡️'} ${c.id} · ${W('ward')} ${c.ward} · ${W('pr')[c.pri]}</span><small class="m">${i?'':'NEXT'}</small></div>`).join('')}</div>`}
p.innerHTML=`<div class="ph-h"><span>Worker portal</span><span class="tag">Worker</span></div><div class="bd2">${h}</div>`;
if(cur){const k=cur.id+cur.st+U.lg;if(U.sk!=k){U.sk=k;const t=(U.fin?W('well')+' ':'')+sayT(w,cur);U.fin=0;setTimeout(()=>speakW(t),300)}}else if(U.fin){U.fin=0;U.sk='';setTimeout(()=>speakW(W('well')),300)}}
let TM={};
function stopLoc(id){if(TM[id]){clearInterval(TM[id].t);TM[id].g!=null&&navigator.geolocation.clearWatch(TM[id].g);delete TM[id]}}
function ploc(m){LOC[m.id]=m;const g=$('#v'+m.id);if(g)g.style.transform=`translate(${m.x}px,${m.y}px)`;else ro();vcs();const w=S.w.find(x=>x.id==U.wid),c=w&&S.c.find(c=>c.w==w.id&&c.st!='RESOLVED'),d=$('#dist');if(d&&c)d.textContent=dist(w,c)}
function startLoc(id){stopLoc(id);const W=()=>S.w.find(x=>x.id==id),put=(x,y,mode,e={})=>{const m={t:'loc',id:W().v,x:Math.max(2,Math.min(98,x)),y:Math.max(2,Math.min(58,y)),mode,ts:now(),...e};ploc(m);bc.postMessage(m);BLOC(m)};let o;
const t=setInterval(()=>{const w=W();if(!w||!w.duty)return stopLoc(id);if(w.mode=='GPS')return;const c=S.c.find(c=>c.w==id&&c.st=='IN_PROGRESS'),p=LOC[w.v]||{x:50,y:30},tx=c?c.x:p.x+(Math.random()-.5)*2,ty=c?c.y:p.y+(Math.random()-.5)*2,d=Math.hypot(tx-p.x,ty-p.y),s=Math.min(1.5,d);put(p.x+(d?(tx-p.x)/d*s:0),p.y+(d?(ty-p.y)/d*s:0),'DEMO',{sp:c&&d>.3?30:0})},700);
let g=null;if(navigator.geolocation)try{g=navigator.geolocation.watchPosition(p=>{const w=W(),k=p.coords;if(!o)o={la:k.latitude,ln:k.longitude};if(w.mode!='GPS'){w.mode='GPS';commit()}put(50+(k.longitude-o.ln)*5550*Math.cos(o.la*Math.PI/180),30-(k.latitude-o.la)*5550,'GPS',{sp:Math.round((k.speed||0)*3.6),acc:Math.round(k.accuracy)})},()=>{},{enableHighAccuracy:true})}catch(e){}TM[id]={t,g}}
/* OPERATOR */
function vcs(){const e=$('#vcs');if(!e)return;e.innerHTML=S.w.map(w=>{const l=LOC[w.v],live=w.duty&&l&&now()-l.ts<8000,mine=S.c.filter(c=>c.w==w.id&&c.st!='MISSED');return`<div class="vc"><b>🚛 ${w.v} · ${w.n}</b><br>${live?'🟢 LIVE':'⚪ Offline'} ${l&&live?(l.mode=='GPS'?'· GPS':'· <span class="tag">DEMO</span>'):''}<br>${live?`${l.sp||0} km/h · Ward ${wardOf(l.x,l.y)} · ${Math.round((now()-l.ts)/1000)}s ago`:'Not on duty'}<br>Tasks ${mine.filter(c=>c.st=='RESOLVED').length}/${mine.length}</div>`}).join('')}
function ask(q){q=q.toLowerCase();const o=S.c.filter(c=>c.st!='RESOLVED'),d0=new Date().setHours(0,0,0,0),td=S.c.filter(c=>c.rt>=d0),L=a=>a.map(c=>`${c.id} (W${c.ward}, ${c.cat}, ${c.pri})`).join('; ')||'none';
if(/miss/.test(q)){const m=S.c.filter(c=>c.st=='MISSED');return`Missed pickups: ${m.length}. ${L(m)}`}
if(/ward/.test(q)){const k={};o.forEach(c=>k[c.ward]=(k[c.ward]||0)+1);const e=Object.entries(k).sort((a,b)=>b[1]-a[1])[0];return e?`Ward ${e[0]} has the most unresolved complaints (${e[1]}).`:'No unresolved complaints.'}
if(/high|priority|unresolved|pending/.test(q)){const h=o.filter(c=>c.pri=='HIGH');return`${h.length} high-priority unresolved: ${L(h)}`}
if(/complet|collect|resolved/.test(q))return`${td.length} collections completed today, ${td.reduce((a,c)=>a+(c.kg||0),0)} kg.`;
if(/vehicle|active|worker/.test(q)){const a=S.w.filter(w=>w.duty);return`${a.length} vehicle(s) on duty: ${a.map(w=>w.v+' ('+w.n+')').join(', ')||'none'}.`}
return'Try: "high-priority unresolved", "completed today", "which ward has most unresolved", "active vehicles", "missed pickups".'}
function suggest(c){let b,bs=1e9;S.w.forEach(w=>{const p=LOC[w.v]||{x:50,y:30},o=S.c.filter(x=>x.w==w.id&&(x.st=='ASSIGNED'||x.st=='IN_PROGRESS')).length,sc=Math.hypot(c.x-p.x,c.y-p.y)+o*15+(w.duty?0:10);if(sc<bs){bs=sc;b=w}});return b}
function ro(){const p=$('#po');if(busy(p))return;const open=S.c.filter(c=>c.st!='RESOLVED'),kg=S.c.reduce((a,c)=>a+(c.kg||0),0),rk=S.c.reduce((a,c)=>a+(RECY.includes(c.wt)?c.kg:0),0),sel=S.c.find(c=>c.id==U.sel),mix={};S.c.forEach(c=>c.kg&&(mix[c.wt]=(mix[c.wt]||0)+c.kg));const mx=Math.max(1,...Object.values(mix));
const asg=c=>c.st=='SUBMITTED'||c.st=='MISSED'?`${suggest(c)?`<button class="btn sm" data-a="qa" data-v="${c.id}" title="Nearest free worker">⚡ ${esc(suggest(c).n)}</button> `:''}<select data-c="pick" data-id="${c.id}" aria-label="Assign ${c.id}"><option value="">Assign…</option>${S.w.map(w=>`<option value="${w.id}">${w.n} · ${w.v}</option>`).join('')}</select>`:(S.w.find(w=>w.id==c.w)||{n:'—'}).n;
p.innerHTML=`<div class="oph"><div><b class="br">Municipal Operations Command Center</b></div><div class="row"><span class="live">SYSTEM LIVE</span><button class="btn sec sm" data-a="sim">＋ Simulate complaint <span class="tag">DEMO</span></button><button class="btn sec sm" data-a="reset">↺ Reset</button></div></div>
<div class="kp">${[['Reports',S.c.length],['Pending',open.length],['Resolved',S.c.length-open.length],['Collected',kg+' kg'],['Recycling rate',(kg?Math.round(rk/kg*100):0)+'%']].map(([a,b])=>`<div class="k"><small>${a}</small><b>${b}</b></div>`).join('')}</div>
<div class="og"><section class="card" style="margin:0"><h3>Live map</h3>${mapH({})}<p class="lgd">🔴 ! New · 🔵 → Assigned · 🟡 ▶ In progress · 🟣 ✕ Missed · 🟢 ✓ Resolved · 🚛 Vehicle</p><div class="vcs" id="vcs"></div>${sel?`<div class="card"><div class="row"><b>${sel.id}</b>${bd(sel.st)}</div><p class="m">Confirmed: ${esc(sel.cat)} · AI: ${sel.ai?sel.ai.cat+' '+Math.round(sel.ai.conf*100)+'%':'n/a'} · ${pb(sel.pri)}</p>${sel.lat?`<p><a href="https://www.google.com/maps?q=${sel.lat},${sel.lng}" target="_blank" rel="noopener">📍 Open exact GPS location</a></p>`:''}${sel.desc?`<p>“${esc(sel.desc)}”</p>`:''}<div class="row">${sel.img?`<img class="th" style="width:48%" src="${sel.img}" alt="Citizen photo">`:''}${sel.proof?`<img class="th" style="width:48%" src="${sel.proof}" alt="Proof of collection">`:''}</div>${sel.kg?`<p>⚖️ ${sel.kg} kg · ♻️ ${sel.wt}</p>`:''}<p class="m">${sel.hist.map(h=>ST[h[0]][1]+' '+tm(h[1])).join(' → ')}</p></div>`:''}</section>
<section class="card" style="margin:0"><h3>Activity</h3><ul class="feed">${S.act.map(a=>`<li><small>${tm(a[0])}</small>${esc(a[1])}</li>`).join('')}</ul></section></div>
<section class="card"><div class="row"><h3>Complaints</h3><select data-c="f" style="width:auto" aria-label="Filter by status"><option value="">All statuses</option>${Object.keys(ST).map(s=>`<option ${U.f==s?'selected':''} value="${s}">${ST[s][1]}</option>`).join('')}</select><button class="btn sm" data-a="auto">⚡ Auto-assign by priority</button></div><div class="tw"><table><tr><th>ID</th><th>Category</th><th>Location</th><th>Priority</th><th>Status</th><th>Assign</th></tr>${S.c.filter(c=>!U.f||c.st==U.f).slice().sort((a,b)=>({SUBMITTED:0,MISSED:0,ASSIGNED:1,IN_PROGRESS:1,RESOLVED:2}[a.st]-{SUBMITTED:0,MISSED:0,ASSIGNED:1,IN_PROGRESS:1,RESOLVED:2}[b.st])||PR[b.pri]-PR[a.pri]||a.t-b.t).map(c=>`<tr class="${c.id==U.sel?'sel':''}"><td><button class="lk" data-a="sel" data-v="${c.id}">${c.id}</button>${c.demo?' <span class="tag">DEMO</span>':''}</td><td>${esc(c.cat)}</td><td>W${c.ward}${c.lat!=null?` · <a href="https://www.google.com/maps?q=${c.lat},${c.lng}" target="_blank" rel="noopener">📍 Map</a>`:''}</td><td>${pb(c.pri)}</td><td>${bd(c.st)}</td><td>${asg(c)}</td></tr>`).join('')}</table></div></section>
<div class="og3"><section class="card" style="margin:0"><h3>♻️ Waste collected by type</h3>${Object.entries(mix).map(([k,v])=>`<div class="bar"><span style="width:62px">${k}</span><i style="width:${v/mx*100}px"></i>${v} kg</div>`).join('')||'<p class="m">No collections yet.</p>'}</section>
<section class="card" style="margin:0"><h3>Ward summary</h3>${[3,7,9,12].map(w=>{const a=S.c.filter(c=>c.ward==w);return`<div class="row"><span>Ward ${w}</span><span class="m">${a.length} reports · ${a.filter(c=>c.st=='RESOLVED').length} resolved</span></div>`}).join('')}</section>
<section class="card" style="margin:0"><h3>🤖 Operations assistant</h3><div class="tx"><input data-u="q" value="${esc(U.q)}" placeholder="e.g. high-priority unresolved" aria-label="Ask the assistant"><button class="btn sm" data-a="ask">Ask</button></div><div class="ans" id="ans" aria-live="polite">${esc(U.ans)}</div></section></div>`;vcs()}
/* ACTIONS */
const A={view(v){document.body.dataset.v=v;scrollTo(0,0);if(v!='cit')gpsStop();R();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('on',b.dataset.v==v))},
cv(v){U.cv=v;if(v=='report')U.rv=0;rc()},lg(v){U.lg=v;document.body.dataset.v=='wk'?rw():rc()},cat(v){U.cat=v;rc()},hear(){const w=S.w.find(x=>x.id==U.wid),c=w&&S.c.filter(c=>c.w==w.id&&(c.st=='ASSIGNED'||c.st=='IN_PROGRESS')).sort((a,b)=>(b.st=='IN_PROGRESS')-(a.st=='IN_PROGRESS')||PR[b.pri]-PR[a.pri])[0];if(c)speakW(sayT(w,c))},missq(){U.mq=!U.mq;rw()},qa(v){const c=S.c.find(c=>c.id==v),w=c&&suggest(c);if(w)assign(v,w.id)},auto(){S.c.filter(c=>c.st=='SUBMITTED'||c.st=='MISSED').sort((a,b)=>PR[b.pri]-PR[a.pri]||a.t-b.t).forEach(c=>{const w=suggest(c);if(w)assign(c.id,w.id)})},sel(v){U.sel=v;ro()},
mic(){const R_=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R_){U.rp='Voice is not supported in this browser. Type below or use the buttons.';return rc()}try{let got=0;const r=new R_();r.lang=T('sr');r.onresult=e=>{got=1;if(U.cv=='report'){U.desc=((U.desc||'')+' '+e.results[0][0].transcript).trim();U.vs='idle';rc();return}U.vs='proc';rc();setTimeout(()=>handle(e.results[0][0].transcript),400)};r.onerror=e=>{if(got)return;U.vs='idle';U.rp={'no-speech':"We didn't hear anything. Tap the mic and try again.",'not-allowed':'Microphone permission is needed. Allow it in the address bar.',aborted:'Listening stopped. Tap the mic to try again.'}[e.error]||'Voice service is unavailable. You can type or use buttons.';rc()};r.onend=()=>{if(U.vs=='listen'){U.vs='idle';rc()}};U.vs='listen';rc();r.start()}catch(e){U.vs='idle';U.rp='Voice service is unavailable. You can type or use buttons.';rc()}},
send(){const t=U.txt.trim();document.activeElement.blur();if(t)handle(t);else rc()},
yes(){if(!U.pend)return;const c=newReport(U.pend.desc);U.pend=null;U.tr='';commit();say(T('done')+' '+c.id)},no(){U.pend=null;U.tr='';U.rp='OK.';rc()},
gps(){U.manual=0;FOL=1;gpsStop();gpsStart();if(MAP&&U.lat!=null)MAP.setView([U.lat,U.lng],Math.max(MAP.getZoom(),17))},cam(v){camera(v)},
submit(){const a=AI(U.desc,U.cat);newReport(U.desc||'',U.cat||a.cat,{img:U.img});gpsStop();Object.assign(U,{cv:'home',desc:'',cat:null,img:null,pri:null,gm:'',lat:null,lng:null,acc:0,manual:0,rv:0});commit()},
duty(){const w=S.w.find(x=>x.id==U.wid);w.duty=w.duty?0:1;w.mode='';w.duty?startLoc(w.id):stopLoc(w.id);log(`${w.duty?'🟢':'⚪'} ${w.n} (${w.v}) ${w.duty?'on duty':'off duty'}`);commit()},
start(){const c=S.c.filter(c=>c.w==U.wid&&c.st=='ASSIGNED').sort((a,b)=>PR[b.pri]-PR[a.pri])[0],w=S.w.find(x=>x.id==U.wid);if(!c)return;if(!w.duty){w.duty=1;startLoc(w.id)}setSt(c,'IN_PROGRESS');if(c.me)note('cit',`🟡 ${c.id}: collection in progress`);note('op',`🚛 ${w.v} started ${c.id}`);commit()},
done(){const c=S.c.find(c=>c.w==U.wid&&c.st=='IN_PROGRESS'),w=S.w.find(x=>x.id==U.wid);if(!c||!U.proof)return;c.proof=U.proof;setSt(c,'RESOLVED');if(c.me)note('cit',`🟢 ${c.id} resolved — the waste has been cleaned.`);note('op',`✅ ${c.id} completed by ${w.n} (${w.v}) — photo proof uploaded`);U.proof=null;U.mq=0;U.fin=1;commit()},
miss(v){const c=S.c.find(c=>c.w==U.wid&&c.st=='IN_PROGRESS');if(!c)return;c.mr=v||'Other';U.mq=0;U.proof=null;setSt(c,'MISSED');if(c.me)note('cit',`⚠️ ${c.id}: pickup missed, will be rescheduled`);note('op',`⚠ Missed pickup ${c.id} — ${c.mr}`);commit()},
ask(){const q=U.q;document.activeElement.blur();U.ans=ask(q);$('#ans').textContent=U.ans},
sim(){const x=5+Math.random()*90,y=4+Math.random()*52,a=CATS[Math.floor(Math.random()*7)],c=mk(NID(),a,x,y,Math.random()<.5?'HIGH':'MED','SUBMITTED',{demo:1,t:now()});c.hist=[['SUBMITTED',now()]];S.c.push(c);note('op',`🔴 NEW ${c.pri} complaint (DEMO) — Ward ${c.ward}: ${c.cat}`);commit()},
reset(){Object.keys(TM).forEach(stopLoc);LOC={};S=seed();U.seen=0;U.sel=null;commit()}};
function assign(id,wid){const c=S.c.find(c=>c.id==id),w=S.w.find(x=>x.id==wid),re=c.st=='MISSED';c.w=wid;setSt(c,'ASSIGNED');note(wid,`🆕 NEW ${c.pri} TASK — Ward ${c.ward}: ${c.cat}`);if(c.me)note('cit',`🔵 ${c.id}: ${re?'rescheduled, ':''}vehicle ${w.v} assigned`);commit()}
function pic(f,k){if(!f)return;const r=new FileReader();r.onload=()=>{const i=new Image();i.onload=()=>{const s=Math.min(1,260/i.width),cv=document.createElement('canvas');cv.width=i.width*s;cv.height=i.height*s;cv.getContext('2d').drawImage(i,0,0,cv.width,cv.height);U[k]=cv.toDataURL('image/jpeg',.6);k=='img'?rc():rw()};i.src=r.result};r.readAsDataURL(f)}
function camera(k){const md=navigator.mediaDevices,msg=m=>{const t=document.createElement('div');t.className='toast';t.innerHTML='<b>Camera</b>'+m;$('#toasts').append(t);setTimeout(()=>t.remove(),5200)};
if(!md||!md.getUserMedia)return msg('Camera is not available here. Open the site over HTTPS or on your phone.');
md.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}).then(st=>{const o=document.createElement('div');o.className='camo';o.setAttribute('role','dialog');o.setAttribute('aria-label','Camera');o.innerHTML='<video playsinline autoplay muted></video><div class="camb"><button class="btn sec" data-x="c">Cancel</button><button class="btn" data-x="s">📸 Capture</button></div>';const v=o.querySelector('video');v.srcObject=st;document.body.append(o);const end=()=>{st.getTracks().forEach(t=>t.stop());o.remove()};o.querySelector('[data-x=c]').onclick=end;o.querySelector('[data-x=s]').onclick=()=>{if(!v.videoWidth)return;const s=Math.min(1,260/v.videoWidth),c=document.createElement('canvas');c.width=v.videoWidth*s;c.height=v.videoHeight*s;c.getContext('2d').drawImage(v,0,0,c.width,c.height);U[k]=c.toDataURL('image/jpeg',.6);end();k=='img'?rc():rw()}}).catch(e=>msg(e&&e.name=='NotFoundError'?'No camera found on this device.':'Camera permission is needed. Allow it in the address bar and try again.'))}
function toasts(){if(S.nid<U.seen)U.seen=S.nid;const v=document.body.dataset.v;S.notes.filter(n=>n.id>U.seen).forEach(n=>{const role=n.to=='op'?'Operator':n.to=='cit'?'Citizen':'Worker '+(S.w.find(w=>w.id==n.to)||{}).n,vis=(n.to=='op'&&v=='op')||(n.to=='cit'&&v=='cit')||(n.to!='op'&&n.to!='cit'&&v=='wk'&&n.to==U.wid);if(vis){const d=document.createElement('div');d.className='toast';d.innerHTML=`<b>${role}</b>${esc(n.m)}`;$('#toasts').append(d);setTimeout(()=>d.remove(),5200)}});U.seen=S.nid}
function R(){toasts();const v=document.body.dataset.v;v=='cit'&&rc();v=='wk'&&rw();v=='op'&&ro()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(b)return A[b.dataset.a]?.(b.dataset.v);const s=e.target.closest('svg[data-m]');if(s){const r=s.getBoundingClientRect();U.px=Math.round((e.clientX-r.left)/r.width*100);U.py=Math.round((e.clientY-r.top)/r.height*60);U.ws=wardOf(U.px,U.py);rc()}});
document.addEventListener('keydown',e=>{if(e.key=='Enter'){const u=e.target.dataset.u;if(u=='txt')A.send();if(u=='q')A.ask();if(e.target.dataset.a=='sel')A.sel(e.target.dataset.v)}});
document.addEventListener('input',e=>{const k=e.target.dataset.u;if(k){U[k]=e.target.value;if(k=='desc'){const a=$('#aib');if(a)a.innerHTML=aib()}if(k=='kg'){const b=document.querySelector('[data-a=done]');if(b)b.disabled=!(U.kg&&U.wt&&U.proof)}}});
document.addEventListener('change',e=>{const t=e.target,c=t.dataset.c;if(!c)return;if(c=='wid'){U.wid=t.value;rw()}else if(c=='pick'&&t.value)assign(t.dataset.id,t.value);else if(c=='f'){U.f=t.value;ro()}else if(c=='img'||c=='proof')pic(t.files[0],c);else U[c=='mr'?'mr':c]=t.value});
document.addEventListener('focusout',()=>setTimeout(()=>{if(U.dirty){U.dirty=0;R()}},60));
bc.onmessage=e=>{if(e.data.t=='s'){S=load();R()}else if(e.data.t=='loc')ploc(e.data)};
$('.tabs').innerHTML=[['cit','Citizen'],['wk','Worker'],['op','Operator']].map(([v,n])=>`<button data-a="view" data-v="${v}" class="${v=='cit'?'on':''}">${n}</button>`).join('');
S.w.filter(w=>w.duty).forEach(w=>{w.duty=0});R();setInterval(vcs,2000);